version: '3.1'

services:
  concurrency:
    image: postgres:13-alpine
    container_name: concurrency
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fresh
      POSTGRES_DB: lock
    ports:
      - "5432:5432"